
POST http://localhost:3000/register
Content-Type: application/json
{
  "name": "Sri FM Akbarisena", 
  "username": "senasena", 
  "email": "emailsena@gmail.com", 
  "phoneNumber": "6281113804506", 
  "address": "Address Sena", 
  "role": "Admin", 
  "password":"SecretAdmin"
}

###
POST http://localhost:3000/login
Content-Type: application/json
